"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { motion } from "framer-motion";
import { useTheme } from "next-themes";
import { Bell, Check, CreditCard, Key, Moon, Search, Settings, Sun, User } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { useUIStore } from "@/store/useUIStore";
import type { OperatorProfile } from "@/lib/db";

const notifications = [
  {
    title: "Latency guardrail triggered",
    body: "auth-service crossed 420ms p95 for 4 minutes.",
    time: "2m ago",
    unread: true,
  },
  {
    title: "API key rotated",
    body: "Production App key was regenerated by admin@aiops.com.",
    time: "17m ago",
    unread: true,
  },
  {
    title: "Weekly report ready",
    body: "Cost, model usage, and error analysis are available.",
    time: "1h ago",
    unread: false,
  },
];

export function Topbar({ profile }: { profile?: OperatorProfile }) {
  const pathname = usePathname();
  const setCommandPaletteOpen = useUIStore((state) => state.setCommandPaletteOpen);
  const { resolvedTheme, setTheme } = useTheme();
  const [readAll, setReadAll] = React.useState(false);
  const [mounted, setMounted] = React.useState(false);

  React.useEffect(() => {
    setMounted(true);
  }, []);

  const isDark = resolvedTheme !== "light";
  const unreadCount = readAll ? 0 : notifications.filter((item) => item.unread).length;

  const pageName =
    pathname === "/dashboard"
      ? "Dashboard"
      : pathname === "/activity"
        ? "Activity"
        : pathname === "/insights"
          ? "Insights"
          : pathname === "/settings"
            ? "Settings"
            : "Overview";

  return (
    <header className="h-14 border-b border-border bg-surface/95 flex items-center px-4 justify-between shrink-0 z-10 backdrop-blur">
      <div className="flex-1 flex items-center">
        <div className="text-sm text-text-muted">
          AIOps Command <span className="mx-1">&gt;</span>{" "}
          <span className="text-text-primary font-medium">{pageName}</span>
        </div>
      </div>

      <div className="flex-1 flex justify-center max-w-md w-full">
        <button
          className="relative w-full cursor-text text-left"
          onClick={() => setCommandPaletteOpen(true)}
        >
          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <Search size={14} className="text-text-muted" />
          </div>
          <div className="block w-full h-9 pl-9 pr-3 rounded-lg bg-surface-dim border border-border text-sm text-text-muted flex items-center justify-between hover:border-text-muted/40 transition-colors">
            <span>Search resources...</span>
            <div className="flex items-center gap-1 opacity-70">
              <kbd className="font-sans text-[10px] bg-background border border-border rounded px-1.5 py-0.5 shadow-sm">
                Ctrl
              </kbd>
              <kbd className="font-sans text-[10px] bg-background border border-border rounded px-1.5 py-0.5 shadow-sm">
                K
              </kbd>
            </div>
          </div>
        </button>
      </div>

      <div className="flex-1 flex items-center justify-end gap-2">
        <Button
          variant="ghost"
          size="icon-lg"
          aria-label="Toggle dark mode"
          onClick={() => setTheme(isDark ? "light" : "dark")}
          className="relative"
        >
          <motion.span
            key={mounted && isDark ? "moon" : "sun"}
            initial={{ opacity: 0, rotate: -20, scale: 0.8 }}
            animate={{ opacity: 1, rotate: 0, scale: 1 }}
            transition={{ duration: 0.18 }}
          >
            {mounted ? (isDark ? <Moon size={17} /> : <Sun size={17} />) : <Moon size={17} className="opacity-0" />}
          </motion.span>
        </Button>

        <Sheet>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon-lg" className="relative" aria-label="Open notifications">
              <Bell size={18} />
              {unreadCount > 0 && (
                <span className="absolute right-2 top-2 flex h-2.5 w-2.5 rounded-full bg-error ring-2 ring-surface" />
              )}
            </Button>
          </SheetTrigger>
          <SheetContent className="w-[380px] sm:max-w-[380px]">
            <SheetHeader>
              <SheetTitle>Notifications</SheetTitle>
              <SheetDescription>Recent system events and account changes.</SheetDescription>
            </SheetHeader>
            <div className="mt-5 flex items-center justify-between rounded-lg border border-border bg-surface-dim p-3">
              <div>
                <div className="text-sm font-medium text-text-primary">Inbox status</div>
                <div className="text-xs text-text-muted">{unreadCount} unread alerts</div>
              </div>
              <Button variant="outline" size="sm" onClick={() => setReadAll(true)}>
                <Check className="mr-1.5 h-3.5 w-3.5" />
                Mark read
              </Button>
            </div>
            <div className="mt-4 space-y-2">
              {notifications.map((item) => {
                const unread = item.unread && !readAll;

                return (
                  <div
                    key={item.title}
                    className={cn(
                      "rounded-lg border border-border bg-surface p-3 transition-colors",
                      unread && "bg-surface-raised"
                    )}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="text-sm font-medium text-text-primary">{item.title}</div>
                        <p className="mt-1 text-xs leading-5 text-text-muted">{item.body}</p>
                      </div>
                      {unread && <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-primary" />}
                    </div>
                    <div className="mt-3 font-mono text-[11px] text-text-muted">{item.time}</div>
                  </div>
                );
              })}
            </div>
          </SheetContent>
        </Sheet>

        <DropdownMenu>
          <DropdownMenuTrigger className="rounded-full outline-none ring-offset-background transition-transform hover:scale-[1.03] focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">
            <Avatar className="h-9 w-9 border border-border bg-surface-dim">
              <AvatarFallback className="bg-surface-dim text-text-primary">
                <User size={16} />
              </AvatarFallback>
            </Avatar>
            <span className="sr-only">Open account menu</span>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-64">
            <DropdownMenuLabel>
              <div className="flex flex-col">
                <span className="text-sm">{profile?.fullName ?? "Morgan Lee"}</span>
                <span className="text-xs font-normal text-text-muted">{profile?.email ?? "admin@aiops.com"}</span>
              </div>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem asChild>
              <Link href="/settings?panel=profile">
                <User className="mr-2 h-4 w-4" />
                Profile
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem asChild>
              <Link href="/settings?panel=api-keys">
                <Key className="mr-2 h-4 w-4" />
                API keys
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem asChild>
              <Link href="/settings?panel=preferences">
                <Settings className="mr-2 h-4 w-4" />
                Preferences
              </Link>
            </DropdownMenuItem>
            <DropdownMenuItem asChild>
              <Link href="/settings?panel=billing">
                <CreditCard className="mr-2 h-4 w-4" />
                Billing
              </Link>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <div className="flex items-center justify-between px-2 py-1.5">
              <span className="text-sm text-text-muted">Dark mode</span>
              {mounted ? (
                <Switch checked={isDark} onCheckedChange={(checked) => setTheme(checked ? "dark" : "light")} />
              ) : (
                <Switch checked={true} disabled />
              )}
            </div>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
}
